

###
GET http://localhost:4000/book_category/products_category/

###
GET http://localhost:4000/book_category/


###
GET http://localhost:4000/product_hot/?limit=12

###
GET http://localhost:4000/products/?limit=4


###
GET http://localhost:4000/product/5

###
POST http://localhost:4000/don_hang/
Content-Type: application/json

{
    "Fullname_nguoi_nhan": "Thu Huynh",
    "Sđt_nguoi_nhan": "090909090",
    "Address_nguoi_nhan": "290 Nam Ky khoi Nghia Q3, TPHCM",
    "Email_nguoi_nhan": "abcd@gmail.com",
    "chi_tiet_don_hang": [
        {
           "Ten": "Ky nang song",
           "So_luong": 1,
           "Don_gia": 40000,
           "Thanh_tien": 40000
        }
    ]
}

###
GET http://localhost:4000/don_hang/abcd_000000000101


